name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
      run: dotnet test --no-build --verbosity normal
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
